### ISSUE TITLE
Confusing option BASE_LOGINPW

### ISSUE THREAD

**Issue by x1ddos** [digitalbitbox/bitbox-base#291]
From the following: https://github.com/digitalbitbox/bitbox-base/blob/d2d75f06f7fcde655209bbb11a01faafa3fb26c1/armbian/base/build.conf#L26-L28

it would seem like this is setting the root password. However, it appears to be doing more than that. What it actually does is locking the user `base` if the root password wasn't set to a custom string in https://github.com/digitalbitbox/bitbox-base/blob/d2d75f06f7fcde655209bbb11a01faafa3fb26c1/armbian/base/customize-armbian-rockpro64.sh#L219-L223

When building the image, I set `BASE_ADD_SSH_KEYS=true` in `armbian/base/build-local.conf` and update `armbian/base/config/ssh/authorized_keys` to contain my ssh key.
I didn't assign any password to `BASE_LOGINPW` because all I want is to ssh with my key as `base` user, and this essentially locked me out.

So, it forces me to do the "unsafe" option, setting `BASE_LOGINPW` to a non-empty string, even though I won't use it.

Additionally, a message during the build is also confusing:

```
CONFIGURATION:
    USER / PASSWORD:    base / some-password
...
```

which would appear as if it was the `base` user password but in reality what it actually does later is:

```
+ BASE_LOGINPW_FINAL=some-password
+ echo root:some-password
+ chpasswd
```

I would suggest being more explicit and rename `BASE_LOGINPW` to something like `BASE_ROOT_PASSWORD` and don't conflate that option with the `base` user at all.

**Comment by Stadicus** [comment]
This is not an easy topic and I won't claim we have the best solution yet, so thanks already for taking the time and going through with it.

For you to use all the features of the BitBoxBase image, you'll always need to use the free open-source BitBoxApp. The build options are mostly meant for development purposes, all advanced settings can later be set in the App. 

When building a **production image**, we don't want to know any password (be it user `root` or `base`) at all. This is why we are setting it to a random string. This is not enought, however, as we could easily learn it during the build process. Therefore, we also lock these users. This prevents anybody from logging in locally by connecting a keyboard and screen.
  * The BitBoxApp is required to configure all advanced settings for production images.
  * Users that want to gain local password login (with keyboard/screen) can "Set system password" in the App (equal to `BASE_LOGINPW`). The passwords for `root` and `base` are kept in sync, but the `root` user always stays locked. --> Local login with user `base` is possible.
  * Users that want to gain SSH access can enable "SSH password login" in the App (equals `SSHPWLOGIN`), configuring the `sshd` to accept a password (`PermitRootLogin` is still disabled) --> Remote ssh login with user `base` is possible.
  * Instead of using the password, when adding a SSH key (that will also be possible with the App), you can login with SSH from the start, but you still need to set the "system password" in the App to execute `sudo`. 
  * To allow root ssh login (e.g. for development), you can run `bbb-config.sh enable rootlogin` on the command line. This is not an option we want to expose in the App. But here it's useful to already have the (locked) `root` password set to the "system password" and not have a separate configuration.

If I understand correctly, you'd like to build a **development image** and add SSH keys from the start, and already setting the "system password" for running `sudo`. You can do that by setting the `BASE_LOGINPW`:
* SSH keys are added
* User `base` password is set for `sudo` use
* User `root` password is set as well, but the user is locked

The only difference to the production image is that the user `base` is not locked.

One thing I think that we can add quite easily is to not set the `root` password together with the `base` password (and, e.g. ask the cli user to change it when running the `bbb-config.sh enable rootlogin` command). Could separate the users more clearly, but is not a real security improvement in my opinion. Do you think that would be worthwile?

Having layed out our thoughts, how would you improve the build options and where do you think the documentation needs improvement?

**Comment by x1ddos** [comment]
Oh, I think I see now. So, the logic goes like this:
"BASE_LOGINPW is non-empty" -> it's a development build
"BASE_LOGINPW is empty" -> it's a production build

Essentially, `BASE_LOGINPW` defines the build mode? If so, it's error prone making it easier to introduce build logic mistakes, twistiing together unrelated options imho.

If the above is how it actually works, I'd suggest creating an explicit option like `BASE_BUILD=dev|prod` and then branching build logic off of that option, i.e. locking useres, generating passwords, stripping binaries, etc.

**Comment by x1ddos** [comment]
In other words, a related question would be: how do I know if I'm doing development or production build?

**Comment by Stadicus** [comment]
Cleaned up build configuration and added binary option `BASE_PRODUCTION_IMAGE`.
