### ISSUE TITLE
Mender alternatives

### ISSUE THREAD

**Issue by x1ddos** [digitalbitbox/bitbox-base#309]
More generally, I'm wondering why A/B partition update was chosen over say [NixOS](https://nixos.org) or [Guix](https://guix.gnu.org) which would provide properties equivalent to those listed as advantages in atomic disk image updates. 

Some reasoning is published at https://base.shiftcrypto.ch/update/update-method.html but it seems to focus only on atomic disk image vs imperative scripts/packages. So, maybe that page could be expanded with more details?

Thanks.

**Comment by TheCharlatan** [comment]
To answer the first question I think mostly, because they pose a significant learning curve in the beginning and none of us were particularly familiar with them at the time. Getting mender working is significantly less overhead compared to creating a full Guix or NixOS configuration.
In my opinion we should seriously consider moving to either of them eventually, not just for their transactional upgrades, but also for better and stricter composability between the services we run on the BitBox-Base. Given that the current system is working though, I don't think that this should be a high priority.

**Comment by Stadicus** [comment]
Thanks @TheCharlatan, can confirm your points. I'd like to add two additioinal reasons:
* working with a existing hardware, we need to choose an operating system that supports the platform. I don't think that either NixOS or Guix are very common in any ARM platform (NixOS cautiously [supports the Pi3](https://nixos.wiki/wiki/NixOS_on_ARM/Raspberry_Pi), but not Pi4, other boards are completely out of the picture)
* one goal would also to move further away from binary distributions to a professional firmware approach like the Yocto project. But as with the other two mentioned projects, that is something further down the road.
