### ISSUE TITLE
Allow compiling Go binaries outside of GOPATH without Docker

### ISSUE THREAD

**Issue by benma** [digitalbitbox/bitbox-base#96]
Currently, we do support building the Go binaries for BitBox Base from any directory using Docker. If the user invokes the default top-level `make` target (or `make docker-build-go`, to build only the Go binaries), everything should Just Work:

* https://github.com/digitalbitbox/bitbox-base/blob/master/Makefile#L16

However, if the user wants to build directly on their system, our build scripts do enforce some requirements on their environment:

* https://github.com/digitalbitbox/bitbox-base/blob/master/scripts/check-go-env.sh#L10

Specifically, they need to check out this repo under `$GOPATH/src/`, since that's a requirement as long as we use `vendor/` setup to manage 3rd party dependencies. See https://github.com/digitalbitbox/bitbox-base/pull/42 and the following page for more context:

* https://github.com/golang/go/wiki/GOPATH#vendor-directories-ignored-outside-of-gopath

It should be possible to remove this restriction if we switched to Go modules:

* https://github.com/golang/go/wiki/Modules#modules

This issue can be closed once a developer with a modern Go toolchain installed can build all Go binaries in this repo without any assumption about where the repo is located in their filesystem.

_Edit:_ Included more context. Original description follows:

_I tried `make -C tools/bbbsupervisor native` and was told to move the repo to `$GOPATH/src/...`._

_As an idea, you could apply a trick like [this](https://github.com/digitalbitbox/bitbox02-firmware/blob/cbdb1ad80de852664d91f4a20660816cd6330ee6/tools/go/src/atecc608a/Makefile#L17) so you can compile it right there. Since bitbox-base is not primarily a Go repo, such an approach might be justified.)_

**Comment by hkjn** [comment]
We do support building from any directory, using Docker. If you invoke the default top-level `make` target (or `make docker-build-go`, to just build the Go binaries), everything should Just Work:

* https://github.com/digitalbitbox/bitbox-base/blob/master/Makefile#L16

If the user wants to build directly on their system, they do need to check out the repo under `$GOPATH/src`, since that's a requirement as long as we use `vendor/` setup to manage 3rd party dependencies:

* https://github.com/digitalbitbox/bitbox-base/blob/master/scripts/check-go-env.sh#L10

See https://github.com/digitalbitbox/bitbox-base/pull/42 for more context.

I believe that it should be possible to remove this restriction if we switched to Go modules:

* https://github.com/golang/go/wiki/Modules#modules

I'll keep this issue open to track the work to remove this restriction, but add some of this context from this reply to its description.

**Comment by Stadicus** [comment]
Closing this issue as fixed
